title: Answer-bot
description: JavaScript bot that tries to recognize input and answers your questions
google_analytics: UA-3067055-6
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
